export enum PartnerStatus {
  PAYMENT_PENDING = "PAYMENT_PENDING",
  CONFIRMATION_PENDING = "CONFIRMATION_PENDING",
  ACTIVE = "ACTIVE",
  RECHARGE_REQUIRED = "RECHARGE_REQUIRED",
  SUSPENDED = "SUSPENDED",
  CANCELED = "CANCELED",
}
